### ISSUE TITLE
The project with the core is not going to Vivado 2019.1

### ISSUE THREAD

**Issue by diy4hobby** [stnolting/neorv32#8] opened 2021-02-13 08:12 UTC
**Describe the bug**
I tried to reproduce the project from the description in Vivado 2019.1, but got parameter type conversion errors:
`[IP_Flow 19-1837] Failed to convert long value '0' to HDL value. Missing bit length for conversion.`
`[IP_Flow 19-3814] Failed to get HDL value for model parameter 'IO_CFS_CONFIG'.`
`[IP_Flow 19-3814] Failed to get HDL value for model parameter 'HW_THREAD_ID'.`
`[IP_Flow 19-3814] Failed to get HDL value for model parameter 'IO_CFS_CONFIG'.`
Perhaps this is due to the fact that my block project is converted to Verilog (and yours to VHDL).

**To Reproduce**
To reproduce it, it is enough to specify in the Vivado settings that convert the block project to Verilog.

**Expected behavior**
For compatibility with different languages, it would like to fix this problem.

Thank you for the project!

**Comment by AWenzel83** [comment] 2021-02-13 10:19
I have the same problem with vhdl, when trying to generate the output products from a block design using the axi top module. 
It works after I open the elaborated design, then it synthesises the design, and it works as intended.

**Comment by diy4hobby** [comment] 2021-02-13 12:19
Thank you, Andreas Wenzel!
Indeed, your method works!
But I still think that this problem should be solved, so that the synthesis and implementation of the project with the core would take place without additional actions.

**Comment by AWenzel83** [comment] 2021-02-13 12:49
Yes you are right, it should really work without this workaround.

**Comment by stnolting** [comment] 2021-02-13 16:26
Thanks for the hint! I haven't noticed that yet.

Seems like Vivado cannot deal with aggregates using just `others` for the default initialization of generics:
https://github.com/stnolting/neorv32/blob/809af1f9804badaf6248bf0c422c01fb43afc084/rtl/top_templates/neorv32_top_axi4lite.vhd#L90

Using a fixed-size initialization like `x"00000000"` instead of `(others => '0')` might solve this problem.

I will evaluate on that and fix it ASAP :wink:

**Comment by diy4hobby** [comment] 2021-02-14 07:34
It seems that the problem is not fixed. I created a completely new core with new sources and getting errors.
![image](https://user-images.githubusercontent.com/77144085/107871151-2771c900-6eb0-11eb-9cfa-007856826d04.png)

**Comment by stnolting** [comment] 2021-02-14 08:18
That is strange. I have also created a new IP-packaging project, a new IP repository and also a new block design using Vivado 2019.2. So far, I do not get any errors.

Which step issued the errors you have mentioned? During "generate output products" or already during "validate design"?

**Comment by stnolting** [comment] 2021-02-17 14:48
@diy4hobby are you still encountering the same error?

**Comment by stnolting** [comment] 2021-03-28 16:49
I am closing this. Feel free to open a new issue if you are still having troubles with the IP packaging. 😉

**Closed by stnolting** 2021-03-28 16:49 UTC
Labels: good first issue
