### ISSUE TITLE
 neorv32/docs/userguide/content.adoc  en dash / em dash 

### ISSUE THREAD

**Issue by lab-mathias-claussen** [stnolting/neorv32#181] opened 2021-10-13 08:33 UTC
In "neorv32/docs/userguide/content.adoc"

The command `./configure --prefix=/opt/riscv --with-arch=rv32i –-with-abi=ilp32`
it shoudl be `./configure --prefix=/opt/riscv --with-arch=rv32i --with-abi=ilp32`

uses wrong dash it seems (en dash vs em dash ) in current adoc.

Regards

**Comment by stnolting** [comment] 2021-10-13 09:29
Eagle eyes!!!
I wasn't aware of these different dash types at all. Seems like this was caused by the old documentation that was written using LibreOffice (auto correction maybe) and I did not actually **see** the em dash when moving to AsciiDoc 😅 

Anyway, thanks for the hint!

**Comment by stnolting** [comment] 2021-10-14 21:24
I think this can be closed.
Feel free to open another issue there are further formatting problems (or any other issues). :wink:

**Closed as completed by stnolting** 2021-10-14 21:24 UTC
Labels: DOC
